### ISSUE TITLE
typos on blog post Automate Podman Containers with Ansible 2/2

### ISSUE THREAD

**Issue by peterclauterbach** [RedHatNordicsSA/RedHatNordicsSA.github.io#4]
Several times on the blog post, Automate Podman Containers with Ansible 2/2, you use "aws", where you mean "awx".

> With only this little amount of automation code (run-aws playbook):
> behind the run-aws.yml playbook you saw in the first chapter
> You see from above that run-aws.yml depends on two Ansible roles:
> 1. aws_pod

https://github.com/RedHatNordicsSA/RedHatNordicsSA.github.io/blob/master/_posts/2019-03-25-ansible-podman-containers-2.markdown

**Comment by ikke-t** [comment]
thanks, fixed it
